version: '3'

services:
  php7.3:
    container_name: php7.3
    build: php7.3/
    image: php7.3
    volumes:
      - ./apache:/etc/apache2/sites-available/
      - ./www:/var/www/html
    ports:
      - "80:80"
    tty: true
  database:
    container_name: database
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%